# Generated by Django 4.2.16 on 2024-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.IntegerField(choices=[(0, 'Finished'), (1, 'Ongoing'), (2, 'Planned')], default=0),
        ),
    ]
