# Generated by Django 4.2.16 on 2024-09-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_comment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
