# Generated by Django 4.2.16 on 2024-09-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_comment_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_on']},
        ),
    ]
