# Generated by Django 4.2.16 on 2024-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_alter_comment_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
