# Generated by Django 4.2.16 on 2024-09-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activity'},
        ),
    ]
