# Generated by Django 4.2.16 on 2024-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_alter_trip_trip_category_alter_trip_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_category',
            field=models.CharField(choices=[('Leisure', 'Leisure'), ('Business', 'Business'), ('Adventure', 'Adventure'), ('Family', 'Family'), ('Romantic', 'Romantic')], max_length=50),
        ),
    ]
