# Generated by Django 4.2.16 on 2024-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_alter_trip_trip_category_alter_trip_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_category',
            field=models.CharField(choices=[('Leisure', 'LEISURE'), ('Business', 'BUSINESS'), ('Adventure', 'ADVENTURE'), ('Family', 'FAMILY'), ('Romantic', 'ROMANTIC')], default='LEISURE', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.IntegerField(choices=[('Completed', 'COMPLETED'), ('Ongoing', 'ONGOING'), ('Planned', 'PLANNED')], default='PLANNED'),
        ),
    ]
