# Generated by Django 4.2.16 on 2024-09-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
