# Generated by Django 4.2.16 on 2024-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0022_alter_trip_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='shared',
            field=models.CharField(choices=[('Yes', 'YES'), ('NO', 'No')], default='YES', max_length=5),
        ),
    ]
