# Generated by Django 4.2.16 on 2024-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0023_alter_trip_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
