# Generated by Django 4.2.16 on 2024-10-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_image_shared_alter_trip_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
    ]
