# Generated by Django 4.2.16 on 2024-10-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0028_alter_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_on', 'country', 'start_date']},
        ),
    ]
