# Generated by Django 4.2.16 on 2024-10-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_testimonial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.TextField(),
        ),
    ]
