# Generated by Django 4.2.16 on 2024-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_testimonial_approved_alter_testimonial_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.CharField(max_length=50),
        ),
    ]
