# Generated by Django 4.2.16 on 2024-10-11 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_testimonial_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_info',
            field=models.CharField(default='Enthusiast user', max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
