# Generated by Django 4.2.16 on 2024-10-11 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_testimonial_author_name_alter_testimonial_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
